# Generated by Django 4.0.6 on 2022-07-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
