# Generated by Django 4.0.6 on 2022-08-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
