# Generated by Django 4.0.6 on 2022-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner_category_banner_is_active_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.AddField(
            model_name='banner',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
