# Generated by Django 4.0.6 on 2022-07-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
